/position_controller:  # uniqe names will be available with HWIF parameter interface
  ros__parameters: 
    joints: 
      - LBRiiwa7Joint1 
      - LBRiiwa7Joint2 
      - LBRiiwa7Joint3 
      - LBRiiwa7Joint4 
      - LBRiiwa7Joint5 
      - LBRiiwa7Joint6 
      - LBRiiwa7Joint7 
    interface_name: position

